//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DiskInspection.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.12.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DA7667502")]
        public string Cam1Sn {
            get {
                return ((string)(this["Cam1Sn"]));
            }
            set {
                this["Cam1Sn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Cam2Sn {
            get {
                return ((string)(this["Cam2Sn"]));
            }
            set {
                this["Cam2Sn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("check_disk_debug")]
        public string EndPointDebug {
            get {
                return ((string)(this["EndPointDebug"]));
            }
            set {
                this["EndPointDebug"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("check_service_status")]
        public string EndPointCheckStatus {
            get {
                return ((string)(this["EndPointCheckStatus"]));
            }
            set {
                this["EndPointCheckStatus"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:8386/ai")]
        public string ApiUrlAi {
            get {
                return ((string)(this["ApiUrlAi"]));
            }
            set {
                this["ApiUrlAi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192.168.0.211")]
        public string PlcIp {
            get {
                return ((string)(this["PlcIp"]));
            }
            set {
                this["PlcIp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public int Cam1Exposure {
            get {
                return ((int)(this["Cam1Exposure"]));
            }
            set {
                this["Cam1Exposure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3000")]
        public int Cam2Exposure {
            get {
                return ((int)(this["Cam2Exposure"]));
            }
            set {
                this["Cam2Exposure"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveEnable {
            get {
                return ((bool)(this["SaveEnable"]));
            }
            set {
                this["SaveEnable"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int SaveMode {
            get {
                return ((int)(this["SaveMode"]));
            }
            set {
                this["SaveMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SavePath {
            get {
                return ((string)(this["SavePath"]));
            }
            set {
                this["SavePath"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("8000")]
        public int PlcPort {
            get {
                return ((int)(this["PlcPort"]));
            }
            set {
                this["PlcPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("connect_plc")]
        public string EndpointConnectPlc {
            get {
                return ((string)(this["EndpointConnectPlc"]));
            }
            set {
                this["EndpointConnectPlc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("disconnect_plc")]
        public string EndpointDisconnectPlc {
            get {
                return ((string)(this["EndpointDisconnectPlc"]));
            }
            set {
                this["EndpointDisconnectPlc"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("control_uv_1")]
        public string EndpointControlUv1 {
            get {
                return ((string)(this["EndpointControlUv1"]));
            }
            set {
                this["EndpointControlUv1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("control_led_1")]
        public string EndpointControlLed1 {
            get {
                return ((string)(this["EndpointControlLed1"]));
            }
            set {
                this["EndpointControlLed1"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("check_connection")]
        public string EndpointCheckConnection {
            get {
                return ((string)(this["EndpointCheckConnection"]));
            }
            set {
                this["EndpointCheckConnection"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("on_error")]
        public string EndpointOnError {
            get {
                return ((string)(this["EndpointOnError"]));
            }
            set {
                this["EndpointOnError"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://127.0.0.1:8386/communication")]
        public string ApiUrlCom {
            get {
                return ((string)(this["ApiUrlCom"]));
            }
            set {
                this["ApiUrlCom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("check_disk_debug_uv")]
        public string EndPointDebugUv {
            get {
                return ((string)(this["EndPointDebugUv"]));
            }
            set {
                this["EndPointDebugUv"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("read_trigger")]
        public string EndpointReadTrigger {
            get {
                return ((string)(this["EndpointReadTrigger"]));
            }
            set {
                this["EndpointReadTrigger"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("reset_trigger")]
        public string EndpointResetTrigger {
            get {
                return ((string)(this["EndpointResetTrigger"]));
            }
            set {
                this["EndpointResetTrigger"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("control_led_2")]
        public string EndpointControlLed2 {
            get {
                return ((string)(this["EndpointControlLed2"]));
            }
            set {
                this["EndpointControlLed2"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("check_disk_white")]
        public string EndpointInspectWhiteLight {
            get {
                return ((string)(this["EndpointInspectWhiteLight"]));
            }
            set {
                this["EndpointInspectWhiteLight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("check_disk_uv")]
        public string EndpointInspectUvLight {
            get {
                return ((string)(this["EndpointInspectUvLight"]));
            }
            set {
                this["EndpointInspectUvLight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime StartShiftTime {
            get {
                return ((global::System.DateTime)(this["StartShiftTime"]));
            }
            set {
                this["StartShiftTime"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CurrentOK {
            get {
                return ((int)(this["CurrentOK"]));
            }
            set {
                this["CurrentOK"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CurrentNG {
            get {
                return ((int)(this["CurrentNG"]));
            }
            set {
                this["CurrentNG"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("control_uv_2")]
        public string EndpointControlUv2 {
            get {
                return ((string)(this["EndpointControlUv2"]));
            }
            set {
                this["EndpointControlUv2"] = value;
            }
        }
    }
}
